auth_enabled: false
server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

common:
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem
