"""add coluna last_notified_at

Revision ID: 0e44da15e26b
Revises: 451d735cb60b
Create Date: 2025-07-08 20:57:24.164771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e44da15e26b'
down_revision: Union[str, None] = '451d735cb60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_notification_logs_channel', table_name='notification_logs')
    op.drop_index('ix_notification_logs_sent_at', table_name='notification_logs')
    op.drop_index('ix_notification_logs_success', table_name='notification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notification_logs_success', 'notification_logs', ['success'], unique=False)
    op.create_index('ix_notification_logs_sent_at', 'notification_logs', ['sent_at'], unique=False)
    op.create_index('ix_notification_logs_channel', 'notification_logs', ['channel'], unique=False)
    op.drop_column('alert_rules', 'last_notified_at')
    # ### end Alembic commands ###
