"""atualizacao_tabelas_produtos

Revision ID: 2265c00ed4a6
Revises: 601779246eda
Create Date: 2025-11-13 20:06:09.237469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2265c00ed4a6'
down_revision: Union[str, None] = '601779246eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('is_paused', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_products', 'is_paused')
    # ### end Alembic commands ###
