"""add_colunas_pausa_monitoramento

Revision ID: 2b10a28c6ee3
Revises: ea326d520b8b
Create Date: 2025-12-19 15:00:16.518094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b10a28c6ee3'
down_revision: Union[str, None] = 'ea326d520b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('monitored_products', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_products', 'paused_at')
    op.drop_column('monitored_products', 'paused')
    # ### end Alembic commands ###
