"""add_campos_estabilidade_coleta

Revision ID: 2f1cbfbf42f9
Revises: 51c1b67084e0
Create Date: 2026-01-16 12:51:55.215546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1cbfbf42f9'
down_revision: Union[str, None] = '51c1b67084e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('competitor_products', sa.Column('last_price_change_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('last_price_change_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('group_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('check_interval', sa.Integer(), nullable=True))
    op.add_column('monitored_products', sa.Column('stability_score', sa.Integer(), nullable=True))
    op.alter_column('users', 'phone_number_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'phone_number_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('monitored_products', 'stability_score')
    op.drop_column('monitored_products', 'check_interval')
    op.drop_column('monitored_products', 'group_collected_at')
    op.drop_column('monitored_products', 'last_price_change_at')
    op.drop_column('monitored_products', 'collected_at')
    op.drop_column('competitor_products', 'last_price_change_at')
    op.drop_column('competitor_products', 'collected_at')
    # ### end Alembic commands ###
