"""remocao_target_price

Revision ID: 30e7e9f99c0f
Revises: e7a4ccf16de5
Create Date: 2025-11-10 20:52:20.358868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e7e9f99c0f'
down_revision: Union[str, None] = 'e7a4ccf16de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'target_price')
    op.drop_column('monitored_products', 'target_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('alert_rules', sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
