"""adiciona_cascade_competitor_products

Revision ID: 3ae29bdedfa3
Revises: 2b10a28c6ee3
Create Date: 2025-12-22 11:21:09.012208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae29bdedfa3'
down_revision: Union[str, None] = '2b10a28c6ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competitor_products_monitored_product_id_fkey', 'competitor_products', type_='foreignkey')
    op.create_foreign_key(None, 'competitor_products', 'monitored_products', ['monitored_product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitor_products', type_='foreignkey')
    op.create_foreign_key('competitor_products_monitored_product_id_fkey', 'competitor_products', 'monitored_products', ['monitored_product_id'], ['id'])
    # ### end Alembic commands ###
