"""atualização coluna search_query para nullable

Revision ID: 3d0ff350638e
Revises: 9a6243bd3a13
Create Date: 2025-06-30 11:51:19.178665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0ff350638e'
down_revision: Union[str, None] = '9a6243bd3a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitored_products', 'search_query',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitored_products', 'search_query',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
