"""add_verificacoes_e_tokens_de_email_phone

Revision ID: 51c1b67084e0
Revises: a4d78328ef13
Create Date: 2026-01-08 18:20:42.065126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c1b67084e0'
down_revision: Union[str, None] = 'a4d78328ef13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type for user_status explicitly to ensure it exists before usage
    user_status = postgresql.ENUM('pending', 'active', 'suspended', name='user_status')
    user_status.create(op.get_bind(), checkfirst=True)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('email', 'phone_number', name='verification_kind'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('otp_hash', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_otp_hash'), 'verifications', ['otp_hash'], unique=True)
    op.create_index(op.f('ix_verifications_token_hash'), 'verifications', ['token_hash'], unique=True)
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)

    # Add new token_hash column as nullable, copy data from old column, then make it not-null
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=128), nullable=True))
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # If previous column 'hashed_token' exists, copy its values to the new column
    op.execute("""
    UPDATE refresh_tokens
    SET token_hash = hashed_token
    WHERE hashed_token IS NOT NULL
    """)
    # Now enforce NOT NULL constraint on token_hash
    op.alter_column('refresh_tokens', 'token_hash', nullable=False)

    # Replace old index/column for hashed_token with new one
    op.drop_index('ix_refresh_tokens_hashed_token', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'hashed_token')

    # Add user verification flags and status safely: add status with default, then enforce not-null
    op.add_column('users', sa.Column('phone_number_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # add status with a temporary server_default so existing rows receive a value
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.Enum('pending', 'active', 'suspended', name='user_status'),
            nullable=True,
            server_default=sa.text("'pending'")
        )
    )
    # Make status not-null and remove the server_default
    op.alter_column('users', 'status', nullable=False, server_default=None)
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'status')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'phone_number_verified')
    op.add_column('refresh_tokens', sa.Column('hashed_token', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_hashed_token', 'refresh_tokens', ['hashed_token'], unique=True)
    op.drop_column('refresh_tokens', 'revoked_at')
    op.drop_column('refresh_tokens', 'token_hash')
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_token_hash'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_otp_hash'), table_name='verifications')
    op.drop_table('verifications')
    # Drop ENUM type for user_status created in upgrade (if it exists)
    user_status = postgresql.ENUM('pending', 'active', 'suspended', name='user_status')
    user_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
