"""add_resumo_comparacao_preco

Revision ID: 601779246eda
Revises: 30e7e9f99c0f
Create Date: 2025-11-13 11:09:20.229677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601779246eda'
down_revision: Union[str, None] = '30e7e9f99c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_comparison_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregates', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['price_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_comparison_summaries_comparison_id'), 'price_comparison_summaries', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_price_comparison_summaries_monitored_product_id'), 'price_comparison_summaries', ['monitored_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_comparison_summaries_monitored_product_id'), table_name='price_comparison_summaries')
    op.drop_index(op.f('ix_price_comparison_summaries_comparison_id'), table_name='price_comparison_summaries')
    op.drop_table('price_comparison_summaries')
    # ### end Alembic commands ###
