"""add_tabela_notificacoes_alertas

Revision ID: 63aae378063e
Revises: acfc4863a6f1
Create Date: 2026-01-06 13:12:15.162335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63aae378063e'
down_revision: Union[str, None] = 'acfc4863a6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('price_change', 'availability_change', 'scraping_error', 'custom', name='alert_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'whatsapp', 'push', 'webhook', name='notification_channel_enum'), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_percent', sa.Float(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'monitored_product_id', 'alert_type', 'channel', name='uq_alert_rule')
    )
    op.create_index(op.f('ix_alert_rule_alert_type'), 'alert_rule', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_rule_monitored_product_id'), 'alert_rule', ['monitored_product_id'], unique=False)
    op.create_index(op.f('ix_alert_rule_user_id'), 'alert_rule', ['user_id'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('price_change', 'availability_change', 'scraping_error', 'custom', name='event_type_enum'), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ocurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_monitored_product_id'), 'event_log', ['monitored_product_id'], unique=False)
    op.create_index(op.f('ix_event_log_trace_id'), 'event_log', ['trace_id'], unique=False)
    op.create_index(op.f('ix_event_log_user_id'), 'event_log', ['user_id'], unique=False)
    op.create_table('user_notification_preference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('price_change', 'availability_change', 'scraping_error', 'custom', name='alert_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'whatsapp', 'push', 'webhook', name='notification_channel_enum'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('channel_metadata', sa.JSON(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'monitored_product_id', 'alert_type', 'channel', name='uq_user_notification_preference')
    )
    op.create_index(op.f('ix_user_notification_preference_monitored_product_id'), 'user_notification_preference', ['monitored_product_id'], unique=False)
    op.create_index(op.f('ix_user_notification_preference_user_id'), 'user_notification_preference', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'sms', 'whatsapp', 'push', 'webhook', name='notification_channel_enum'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'sent', 'failed', 'skipped', name='notification_status_enum'), nullable=False),
    sa.Column('dedup_hash', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'recipient', 'channel', name='uq_notification_event_recipient_channel')
    )
    op.create_index(op.f('ix_notifications_alert_id'), 'notifications', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notifications_dedup_hash'), 'notifications', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_monitored_product_id'), 'notifications', ['monitored_product_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('price_comparison_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregates', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['price_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_comparison_summaries_comparison_id'), 'price_comparison_summaries', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_price_comparison_summaries_monitored_product_id'), 'price_comparison_summaries', ['monitored_product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('competitor_product_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(monitored_product_id IS NOT NULL) OR (competitor_product_id IS NOT NULL)', name='price_history_owner_check'),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['competitor_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_competitor_product_id'), 'price_history', ['competitor_product_id'], unique=False)
    op.create_index(op.f('ix_price_history_monitored_product_id'), 'price_history', ['monitored_product_id'], unique=False)
    op.create_table('notification_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='delivery_status_enum'), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_attempt_notification_id'), 'notification_attempt', ['notification_id'], unique=False)
    op.add_column('competitor_products', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('monitored_products', sa.Column('currency', sa.String(length=8), nullable=True))
    op.drop_column('monitored_products', 'target_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('monitored_products', 'currency')
    op.drop_column('competitor_products', 'currency')
    op.drop_index(op.f('ix_notification_attempt_notification_id'), table_name='notification_attempt')
    op.drop_table('notification_attempt')
    op.drop_index(op.f('ix_price_history_monitored_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_competitor_product_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_price_comparison_summaries_monitored_product_id'), table_name='price_comparison_summaries')
    op.drop_index(op.f('ix_price_comparison_summaries_comparison_id'), table_name='price_comparison_summaries')
    op.drop_table('price_comparison_summaries')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_monitored_product_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_hash'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_user_notification_preference_user_id'), table_name='user_notification_preference')
    op.drop_index(op.f('ix_user_notification_preference_monitored_product_id'), table_name='user_notification_preference')
    op.drop_table('user_notification_preference')
    op.drop_index(op.f('ix_event_log_user_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_trace_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_monitored_product_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_alert_rule_user_id'), table_name='alert_rule')
    op.drop_index(op.f('ix_alert_rule_monitored_product_id'), table_name='alert_rule')
    op.drop_index(op.f('ix_alert_rule_alert_type'), table_name='alert_rule')
    op.drop_table('alert_rule')
    # ### end Alembic commands ###
