"""add_campos_comportamento_tasks_celery

Revision ID: 78ab441b37e5
Revises: 67e3d60782f2
Create Date: 2025-12-11 12:05:48.897026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ab441b37e5'
down_revision: Union[str, None] = '67e3d60782f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('checking_in_progress', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('monitored_products', sa.Column('checking_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_monitored_products_next_check_at'), 'monitored_products', ['next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_products_next_check_at'), table_name='monitored_products')
    op.drop_column('monitored_products', 'next_check_at')
    op.drop_column('monitored_products', 'checking_started_at')
    op.drop_column('monitored_products', 'checking_in_progress')
    # ### end Alembic commands ###
