"""criação da tabela comparisons

Revision ID: 9a6243bd3a13
Revises: 11c1fb9c8aad
Create Date: 2025-06-11 18:49:38.577935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6243bd3a13'
down_revision: Union[str, None] = '11c1fb9c8aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_comparisons_monitored_product_id'), 'price_comparisons', ['monitored_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_comparisons_monitored_product_id'), table_name='price_comparisons')
    op.drop_table('price_comparisons')
    # ### end Alembic commands ###
