"""add_campo_dead_letter_notificacao_nao_enviada

Revision ID: a4d78328ef13
Revises: ba0cc453aabf
Create Date: 2026-01-07 14:28:34.583500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d78328ef13'
down_revision: Union[str, None] = 'ba0cc453aabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_attempt', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'dead_lettered_at')
    op.drop_column('notification_attempt', 'provider_message_id')
    # ### end Alembic commands ###
