"""remocao_alertas_notificacoes

Revision ID: acfc4863a6f1
Revises: 3ae29bdedfa3
Create Date: 2025-12-29 17:27:17.942325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acfc4863a6f1'
down_revision: Union[str, None] = '3ae29bdedfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use IF EXISTS to avoid failures when objects are already absent
    op.execute("DROP INDEX IF EXISTS ix_alert_rules_monitored_product_id")
    op.execute("DROP INDEX IF EXISTS ix_alert_rules_user_id")
    op.execute("DROP TABLE IF EXISTS alert_rules CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_notification_logs_alert_rule_id")
    op.execute("DROP INDEX IF EXISTS ix_notification_logs_comparison_id")
    op.execute("DROP INDEX IF EXISTS ix_notification_logs_user_id")
    op.execute("DROP TABLE IF EXISTS notification_logs CASCADE")
    op.execute("ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS notifications_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', 'PUSH', 'WHATSAPP', 'WEBHOOK', name='notification_channel_enum'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('alert_type', postgresql.ENUM('price_target', 'price_change', 'listing_paused', 'listing_removed', 'scraping_error', 'scraping_blocked', 'scraping_suspended', 'circuit_breaker_open', 'cache_miss_rate_high', 'system_error', name='notification_alert_type_enum'), autoincrement=False, nullable=True),
    sa.Column('provider_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comparison_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='notification_severity_enum'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SENT', 'FAILED', 'SKIPPED_COOLDOWN', 'SKIPPED_DUPLICATE', 'SKIPPED_TOLERANCE', name='notification_status_enum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name='notification_logs_alert_rule_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notification_logs_pkey')
    )
    op.create_index('ix_notification_logs_user_id', 'notification_logs', ['user_id'], unique=False)
    op.create_index('ix_notification_logs_comparison_id', 'notification_logs', ['comparison_id'], unique=False)
    op.create_index('ix_notification_logs_alert_rule_id', 'notification_logs', ['alert_rule_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rule_type', postgresql.ENUM('PRICE_TARGET', 'PRICE_CHANGE', 'LISTING_PAUSED', 'LISTING_REMOVED', 'SCRAPING_ERROR', 'SCRAPING_BLOCKED', 'SCRAPING_SUSPENDED', 'CIRCUIT_BREAKER_OPEN', 'CACHE_MISS_RATE_HIGH', 'SYSTEM_ERROR', name='alert_rule_type_enum'), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('threshold_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('product_status', postgresql.ENUM('available', 'unavailable', 'removed', 'pending', name='product_status_enum'), autoincrement=False, nullable=True),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], name='alert_rules_monitored_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='alert_rules_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alert_rules_pkey')
    )
    op.create_index('ix_alert_rules_user_id', 'alert_rules', ['user_id'], unique=False)
    op.create_index('ix_alert_rules_monitored_product_id', 'alert_rules', ['monitored_product_id'], unique=False)
    # ### end Alembic commands ###
