"""atualizar_alinhar_tabelas_comparacao

Revision ID: c9aa1b63b5ed
Revises: 2265c00ed4a6
Create Date: 2025-11-14 19:23:19.456345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9aa1b63b5ed'
down_revision: Union[str, None] = '2265c00ed4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to ensure enum types exist ###
    # Create ENUM types first (Postgres requires the type to exist before using it in a column)
    notification_severity = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='notification_severity_enum')
    notification_status = sa.Enum(
        'SENT', 'FAILED', 'SKIPPED_COOLDOWN', 'SKIPPED_DUPLICATE', 'SKIPPED_TOLERANCE',
        name='notification_status_enum'
    )

    notification_severity.create(op.get_bind(), checkfirst=True)
    notification_status.create(op.get_bind(), checkfirst=True)

    op.add_column('notification_logs', sa.Column('comparison_id', sa.UUID(), nullable=True))
    op.add_column('notification_logs', sa.Column('severity', notification_severity, nullable=True))
    op.add_column('notification_logs', sa.Column('status', notification_status, nullable=False))
    op.create_index(op.f('ix_notification_logs_comparison_id'), 'notification_logs', ['comparison_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to drop enums after columns ###
    op.drop_index(op.f('ix_notification_logs_comparison_id'), table_name='notification_logs')
    op.drop_column('notification_logs', 'status')
    op.drop_column('notification_logs', 'severity')
    op.drop_column('notification_logs', 'comparison_id')

    # Drop ENUM types (safe with checkfirst=True)
    notification_severity = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='notification_severity_enum')
    notification_status = sa.Enum(
        'SENT', 'FAILED', 'SKIPPED_COOLDOWN', 'SKIPPED_DUPLICATE', 'SKIPPED_TOLERANCE',
        name='notification_status_enum'
    )

    notification_status.drop(op.get_bind(), checkfirst=True)
    notification_severity.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
