"""add_registrar_metadados_scraping

Revision ID: c9ffaa81420d
Revises: 7e1702a5fefd
Create Date: 2025-11-21 12:26:01.185619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ffaa81420d'
down_revision: Union[str, None] = '7e1702a5fefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_competitor_products_last_scraped_at'), 'competitor_products', ['last_scraped_at'], unique=False)
    op.add_column('monitored_products', sa.Column('normalized_url', sa.Text(), nullable=False))
    op.add_column('monitored_products', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('monitored_products', sa.Column('last_scrape_signature', sa.String(), nullable=True))
    op.add_column('monitored_products', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('uq_user_product_url', 'monitored_products', type_='unique')
    op.create_index(op.f('ix_monitored_products_last_scraped_at'), 'monitored_products', ['last_scraped_at'], unique=False)
    op.create_index(op.f('ix_monitored_products_name'), 'monitored_products', ['name'], unique=False)
    op.create_index(op.f('ix_monitored_products_normalized_url'), 'monitored_products', ['normalized_url'], unique=False)
    op.create_unique_constraint('uq_user_normalized_url', 'monitored_products', ['user_id', 'normalized_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_normalized_url', 'monitored_products', type_='unique')
    op.drop_index(op.f('ix_monitored_products_normalized_url'), table_name='monitored_products')
    op.drop_index(op.f('ix_monitored_products_name'), table_name='monitored_products')
    op.drop_index(op.f('ix_monitored_products_last_scraped_at'), table_name='monitored_products')
    op.create_unique_constraint('uq_user_product_url', 'monitored_products', ['user_id', 'product_url'])
    op.drop_column('monitored_products', 'last_scraped_at')
    op.drop_column('monitored_products', 'last_scrape_signature')
    op.drop_column('monitored_products', 'is_featured')
    op.drop_column('monitored_products', 'normalized_url')
    op.drop_index(op.f('ix_competitor_products_last_scraped_at'), table_name='competitor_products')
    op.drop_column('competitor_products', 'last_scraped_at')
    # ### end Alembic commands ###
