"""atualizacao_tabelas_apos_integrar_servicos

Revision ID: e7a4ccf16de5
Revises: 3b4d9f552a78
Create Date: 2025-10-31 18:08:27.776945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a4ccf16de5'
down_revision: Union[str, None] = '3b4d9f552a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitored_product_id', sa.UUID(), nullable=True),
    sa.Column('competitor_product_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(monitored_product_id IS NOT NULL) OR (competitor_product_id IS NOT NULL)', name='price_history_owner_check'),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['competitor_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_product_id'], ['monitored_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_competitor_product_id'), 'price_history', ['competitor_product_id'], unique=False)
    op.create_index(op.f('ix_price_history_monitored_product_id'), 'price_history', ['monitored_product_id'], unique=False)
    op.add_column('competitor_products', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('monitored_products', sa.Column('currency', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_products', 'currency')
    op.drop_column('competitor_products', 'currency')
    op.drop_index(op.f('ix_price_history_monitored_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_competitor_product_id'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
