"""inclui_availability_tabela_produtos

Revision ID: ea326d520b8b
Revises: 7475b688335b
Create Date: 2025-12-17 11:45:14.543271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea326d520b8b'
down_revision: Union[str, None] = '7475b688335b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('availability', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('competitor_products', sa.Column('last_status', sa.Text(), nullable=True))
    op.add_column('monitored_products', sa.Column('availability', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('monitored_products', sa.Column('last_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_products', 'last_status')
    op.drop_column('monitored_products', 'availability')
    op.drop_column('competitor_products', 'last_status')
    op.drop_column('competitor_products', 'availability')
    # ### end Alembic commands ###
