global:
  scrape_interval: 15s #A cada 15 segundos, coleta métricas
  evaluation_interval: 15s #A cada 15 segundos avalia regras de alerta

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert_rules.yml


scrape_configs:
  #Fastapi (principal)
  - job_name: marketalert_app
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  #Audit Exporter (arquivos de auditoria)
  - job_name: marketalert_audit
    metrics_path: /audit/metrica
    static_configs:
        - targets: ["api:8000"]

  #Celery Beat
  - job_name: marketalert_celery
    metrics_path: /metrics
    static_configs:
      - targets: ["celery_beat:8001"]

  #Celery worker
  - job_name: marketalert_worker
    metrics_path: /metrics
    static_configs:
      - targets: ["celery-worker:8002"]

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
