"""Adicionado colunas etag/last_modified e campos em scraping_errors

Revision ID: 11c1fb9c8aad
Revises: 534105d807a1
Create Date: 2025-06-02 12:01:12.264327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c1fb9c8aad'
down_revision: Union[str, None] = '534105d807a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_products', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('competitor_products', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitored_products', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('monitored_products', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scraping_errors', sa.Column('stage', sa.String(length=50), nullable=False))
    op.add_column('scraping_errors', sa.Column('http_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_errors', 'http_status')
    op.drop_column('scraping_errors', 'stage')
    op.drop_column('monitored_products', 'last_modified')
    op.drop_column('monitored_products', 'etag')
    op.drop_column('competitor_products', 'last_modified')
    op.drop_column('competitor_products', 'etag')
    # ### end Alembic commands ###
