"""add colunas alert_type e provider_metadata em NotificationLog

Revision ID: 5e41b7f3a907
Revises: bf6bc6bd5d2b
Create Date: 2025-07-04 19:37:42.011649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e41b7f3a907'
down_revision: Union[str, None] = 'bf6bc6bd5d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    alert_enum = sa.Enum(
        'price_target',
        'price_change',
        'listing_paused',
        'listing_removed',
        'scraping_error',
        'scraping_blocked',
        'scraping_suspended',
        'circuit_breaker_open',
        'cache_miss_rate_high',
        'system_error',
        name='notification_alert_type_enum'
    )
    alert_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('alert_type', alert_enum, nullable=True))
    op.add_column('notification_logs', sa.Column('provider_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    alert_enum = sa.Enum(
        'price_target',
        'price_change',
        'listing_paused',
        'listing_removed',
        'scraping_error',
        'scraping_blocked',
        'scraping_suspended',
        'circuit_breaker_open',
        'cache_miss_rate_high',
        'system_error',
        name='notification_alert_type_enum'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_logs', 'provider_metadata')
    op.drop_column('notification_logs', 'alert_type')
    alert_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###