"""add novas colunas target_price e product_status em models_alerts

Revision ID: bf6bc6bd5d2b
Revises: 96fe3b479acc
Create Date: 2025-07-04 18:57:03.812550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6bc6bd5d2b'
down_revision: Union[str, None] = '96fe3b479acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('alert_rules', sa.Column('product_status', sa.Enum('available', 'unavailable', 'removed', name='product_status_enum'), nullable=True))
    op.add_column('notification_logs', sa.Column('subject', sa.Text(), nullable=False))
    op.add_column('notification_logs', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_logs', 'sent_at')
    op.drop_column('notification_logs', 'subject')
    op.drop_column('alert_rules', 'product_status')
    op.drop_column('alert_rules', 'target_price')
    # ### end Alembic commands ###
