{
 "title": "Métricas Celery - MarketAlert",
 "tags": [
  "celery",
  "marketalert"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Taxa de Execução de Tarefas por Nome (min)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_total[1m])) by (task_name)",
     "legendFormat": "Tarefa: {{task_name}}"
    }
   ]
  },
  {
   "title": "Taxa de Execução de Tarefas por Status (min)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_total[1m])) by (status)",
     "legendFormat": "{{status == 'success' ? 'Concluídas' : 'Com falha'}}"
    }
   ]
  },
  {
   "title": "Falhas de Tarefas (min)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 7, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_total{status=\"failure\"}[1m]))",
     "legendFormat": "Falhas/min"
    }
   ]
  },
  {
   "title": "Numero de Workers Ativos",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 7, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(celery_workers_total)", "legendFormat": "Workers Ativos" }
   ]
  },
  {
   "title": "Tarefas Pendentes na Fila",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 7, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(celery_queue_length)", "legendFormat": "Pendentes" }
   ]
  },
  {
   "title": "Concorrência Total por Worker",
   "type": "gauge",
   "gridPos": { "x": 18, "y": 7, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(celery_worker_concurrency)", "legendFormat": "Threads" }
   ]
  },
  {
   "title": "Heatmap de Latência de Tarefas (min)",
   "type": "heatmap",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_duration_seconds_bucket[5m])) by (le, task_name)",
     "legendFormat": "Tarefa: {{task_name}}"
    }
   ]
  },
  {
   "title": "Histograma de Latência de Tarefas (P99)",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(celery_task_duration_seconds_bucket[5m])) by (le, task_name))",
     "legendFormat": "Tarefa: {{task_name}}"
    }
   ]
  }
 ]
}